name: saints
description: Lives of saints

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.1.0+25

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  easy_localization: ^3.0.0
  rate_my_app: ^2.0.0
  flutter_svg: ^2.0.5
  sqflite: ^2.2.8+3
  supercharged: ^2.1.1
  html2md: ^1.2.6
  rxdart: ^0.27.7
  store_redirect: ^2.0.0
  jiffy: ^6.1.0
  quiver: ^3.2.1
  fluttertoast: ^8.2.1
  launch_review: ^3.0.1
  gallery_saver: ^2.3.2
  share_plus: ^8.0.0

  flutter_toolkit:
    path: /Users/alexey/workspace/flutter_toolkit

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/saints_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/db/
    - assets/icons/
    - assets/images/
    - assets/translations/
